version: "3.9"

services:
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: ./Dockerfile.api
    ports:
      - 8080:80
  frontend:
    container_name: "frontend"
    build:
      context: frontend
    ports:
      - 3000:80
