version: "3.9"

services:
  api:
    container_name: "api"
    image: axrez/devops-backend
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:80

  frontend:
    container_name: "frontend"
    image: axrez/devops-frontend
    depends_on:
      - db
    ports:
      - 80:80
