version: "3.9"

#der skal laves volume til grafana

networks: 
  main:
    name: main

services:
 
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.2.0"
    container_name: "elasticsearch"
    environment:
      - discovery.type=single-node
    ports: 
      - 9200:9200
    networks:
      - main

  kibana:
   container_name: kibana
   image: "docker.elastic.co/kibana/kibana:7.2.0"
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   environment:
    elasticsearch.hosts: '["http://elasticsearch:9200"]'
   networks:
    - main
        
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: ./Dockerfile.api
    depends_on:
      - elasticsearch
    ports:
      - 8080:80
    networks:
      - main

  frontend:
    container_name: "frontend"
    build:
      context: frontend
    ports:
      - 3001:80
    networks:
      - main

  grafana:
   image: grafana/grafana:latest
   ports:
     - 3000:3000  
   networks:
     - main
   volumes:
    - grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prom:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - main    


volumes:
  grafana-storage:
  prom: 

