version: "3.9"

services:
  db: 
    container_name: "db"
    image: mcr.microsoft.com/azure-sql-edge
    environment: 
      MSSQL_SA_PASSWORD: "Belnis12456!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports: 
      - 1433:1433  

  api:
    container_name: "api"
    image: axrez/devops-backend
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:80

  frontend:
    container_name: "frontend"
    image: axrez/devops-frontend
    depends_on:
      - db
    ports:
      - 80:80
