version: "3.9"

networks: 
  main:
    name: minitwat


services:
  db: 
      container_name: "db"
      image: mcr.microsoft.com/azure-sql-edge
      environment: 
        MSSQL_SA_PASSWORD: "Belnis12456!"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Developer" 
        
  api:
    container_name: "api"
    image: axrez/devops-backend
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:80

  frontend:
    container_name: "frontend"
    image: axrez/devops-frontend
    depends_on:
      - db
    ports:
      - 8081:80

  grafana:
   image: grafana/grafana:latest
   ports:
     - 3000:3000  
   networks:
     - main
   volumes:
    - grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prome:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    #command: --web.enable-lifecycle  --config.file=prometheus.yml  
    ports:
      - "9090:9090"
    networks:
      - main    

volumes:
  grafana-storage:
  prome: 