version: "3.9"

#der skal laves volume til grafana

networks: 
  main:
    name: minitwat

services:
  db: 
      container_name: "db"
      image: mcr.microsoft.com/azure-sql-edge
      environment: 
        MSSQL_SA_PASSWORD: "Belnis12456!"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Developer"
      ports: 
        - 1433:1433  

  api:
    container_name: "api"
    build:
      context: .
      dockerfile: ./Dockerfile.api
    depends_on:
      - db
    ports:
      - 8080:80

  frontend:
    container_name: "frontend"
    build:
      context: frontend
    ports:
      - 3001:80

  grafana:
   image: grafana/grafana:latest
   ports:
     - 3000:3000  
   networks:
     - main
   volumes:
    - grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prom:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - main    
        

volumes:
  grafana-storage:
  prom: 

