version: "3.9"

services:
  api:
    container_name: "api"
    image: axrez/devops-backend
    environment:
      - IP
    ports:
      - 8080:80

  sim_api:
    container_name: "sim-api"
    image: axrez/devops-simapi
    ports:
      - 8081:80

  frontend:
    container_name: "frontend"
    image: axrez/devops-frontend
    environment:
      - REACT_APP_BASE_URL
    ports:
      - 80:80
#api kan kaldes via url http://localhost:8080 f.eks. http://localhost:8080/user/usermessages
