version: "3.9"

services:
  db: 
    container_name: "db"
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment: 
      MSSQL_SA_PASSWORD: "Belnis12456!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports: 
      - 1433:1433  
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: ./Dockerfile.api
    ports:
      - 8080:80

  frontend:
    container_name: "frontend"
    build:
      context: frontend
    ports:
      - 3000:80

  sim_api:
    container_name: "sim-api"
    build:
      dockerfile: Dockerfile_simapi
      context: .
    #image: axrez/devops-simapi
    ports:
      - 8081:80

