# Mostly directly from cirlce ci's docs
# https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
version: 2
jobs:
  build:
    docker:
     - image: cimg/base:2022.02
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: docker build -t axrez/frontend -f frontend/Dockerfile frontend
      - run: |
          echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
          docker push axrez/frontend

  build-backend:
    docker:
     - image: cimg/base:2022.02
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: docker build -t axrez/backend -f Dockerfile.api .
      - run: |
          echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
          docker push axrez/backend
  deploy-to-digital-ocean:
    docker:
     - image: cimg/base:2022.02
    resource_class: small
    steps:
      - run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && apt-get install vagrant
          vagrant plugin install vagrant-digitalocean
      - run: vagrant rebuild
workflows:
  version: 2
  build:
    jobs:
      - "build"
      - "build-backend"
      - deploy-to-digital-ocean:
        #requires:
        #- build
        #- build-backend
