# Mostly directly from cirlce ci's docs
# https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
version: 2
jobs:
  build:
    steps:
      - checkout
      - run: docker build -t axrez/frontend -f frontend/Dockerfile frontend
      - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
          docker push axrez/frontend

