# Mostly directly from cirlce ci's docs
# https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
version: 2
jobs:
  build:
    docker:
     - image: cimg/base:2022.02
    resource_class: small
    steps:
      - checkout
      - run: docker build -t axrez/frontend -f frontend/Dockerfile frontend
      - run: |
          echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
          docker push axrez/frontend

