name: CI
on: pull_request
jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i
    - name: Run ESLint
      run: npm run lint
    - name: npm run build